# Worker Config
workers_dev = true
compatibility_date = "2022-06-26"
main = "./.cloudflare/worker.mjs"
site.bucket = "./.cloudflare/public"
build.command = "npm run build"

# Crons
[triggers]
crons = ["*/30 * * * *"]

# Durable Objects
[[migrations]]
tag = "v1"
new_classes = ["CDNStats"]

# Environments
[env.stg]
name = "biowasm-v3-stg"
routes = [{ pattern = "stg.biowasm.com/*", zone_name = "biowasm.com" }]
vars = { ENVIRONMENT = "stg" }
kv_namespaces = [
	{ binding = "CDN", id = "ceb6fce5bbe54655a0ca3add95d29954" },
	{ binding = "CDN_V2", id = "51cfc57233574476be9cd5bb2252dc79" }
]
durable_objects = { bindings = [{ name = "stats", class_name = "CDNStats" }] }

[env.prd]
name = "biowasm-v3-prd"
routes = [{ pattern = "biowasm.com/*", zone_name = "biowasm.com" }]
vars = { ENVIRONMENT = "prd" }
kv_namespaces = [
	{ binding = "CDN", id = "2ddb9221f3e64a0a9f113971204a8675" },
	{ binding = "CDN_V2", id = "51cfc57233574476be9cd5bb2252dc79" }
]
durable_objects = { bindings = [{ name = "stats", class_name = "CDNStats" }] }
