
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/var/lib/snapd/snap/clion/263/bin/cmake/linux/x64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.6.10-1-MANJARO - x86_64
...
