### get all events
POST http://svc-fer-dev.helpms.ru:3333/v1/event/list
Content-Type: application/json

### get all events with page
POST http://svc-fer-dev.helpms.ru:3333/v1/event/list
Content-Type: application/json

{
  "page": {
    "limit": 1,
    "offset": 2
  }
}