name: Aioli Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run tests
        run: npm install && npm run test
