name: Tests

# Run twice a day (2am/2pm UTC), after deploys, or manually
on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:
    inputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout biowasm repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Run tests
        run: |
          cd web/
          npm install
          npm run test
